name: openpark
description: ""

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.1
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  dio: ^5.3.2
  shared_preferences: ^2.2.0
  image_picker: ^1.0.4
  google_mlkit_text_recognition: ^0.15.0
  path_provider: ^2.1.1
  permission_handler: ^12.0.0+1
  path: ^1.8.3
  flutter_local_notifications: ^19.2.1
  android_alarm_manager_plus: ^4.0.7
  universal_platform: ^1.1.0
  opp_api_client:
    git:
      url: https://github.com/OpenParkProject/OPP-common.git
      ref: dart-dio-client
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/background.jpg
    - assets/data/db_zones.csv
    - assets/images/avatar.png
