name: Flutter Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build Linux
        run: flutter build linux --release

      - name: Build Web
        run: flutter build web --release

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-builds
          path: |
            build/linux/**/release/**
            build/web/**
            build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: warn

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: flutter-builds
          path: artifacts/

      - name: List downloaded files
        run: ls -R artifacts/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**

  trigger-iac:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Trigger repository_dispatch in OPP-IaC
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          repository: OpenParkProject/OPP-IaC
          event-type: OPP-frontend-updated
