name: Flutter Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project
        run: flutter analyze --no-fatal-infos

      - name: Run tests
        run: flutter test

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libgtk-3-dev liblzma-dev \
          libpango1.0-dev \
          libglib2.0-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev

      - name: Build Linux
        run: flutter build linux --release

      - name: Build Web
        run: flutter build web --release
        
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-builds
          path: |
            build/linux/**/release/**
            build/web/**
            build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: warn

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: flutter-builds
          path: artifacts/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**