name: trigger-iac
on:
  push:
    branches: [main]

  trigger-iac:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository_dispatch in OPP-IaC
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          repository: OpenParkProject/OPP-IaC
          event-type: frontend-updated
